################################################################################
# Author: Mr.Nobody
# file:  IntegrationTesting_Detect.cmake
# brief: Detection of boards connected to debug probes - writes the boards file
#        of the connected boards (Build/IntegrationTestBoards.json).
#
# Usage (from the project root folder with CMakePresets.json):
#   cmake -P EmBi_Platform/CMake/IntegrationTesting/IntegrationTesting_Detect.cmake
# or included by host scripts (IntegrationTesting_DetectBoards).
#
# Every connected probe (probe-rs list) is identified by the MCU identification
# of the Ral presets (Bsp/Ral/RalPresets.json, IntegrationTesting_Probe.cmake) -
# ID register and flash size register are read with a generic core, matching
# MCUs with integration test preset <MCU>_IntegrationTest in the project
# CMakePresets.json are the candidates of the probe.
#
# Boards file of the project (IntegrationTestBoards.json in the project root) is
# optional - an override of the detected boards:
#   { "boards": { "<board>": { "preset": "<MCU>_IntegrationTest",
#                              "probes": [ "<VID:PID:SN or SN>", ... ],
#                              "cacheVariables": { "INTEGRATION_TEST_...": "<value>" } } } }
#   - board with "probes" gets these probes (if connected), MCU of the probe is
#     not checked here (the run script checks it before download)
#   - board without "probes" gets all connected probes whose MCU matches its
#     preset (eg. name of the board, ambiguous ID - STM32F405/F407 share DEV_ID)
#   - cacheVariables are passed to the configuration of the board
# Other identified probes create boards named by the MCU - of more candidates
# (same ID and flash size, eg. STM32G411xB / G431xB / G441xB) the first one
# whose device probe-rs knows (the firmware can be executed), otherwise the
# first one; the other candidates are reported. Probes without identified MCU
# are reported.
#
# Output (not versioned, regenerated by every detection):
#   { "boards": { "<board>": { "preset": "...", "probes": [ ... ], "cacheVariables": { ... } } } }
#
# Optional parameters:
#   IT_MCU_PRESETS_FILE  - MCU identification (default Bsp/Ral/RalPresets.json)
#   IT_BOARDS_OVERRIDE   - Boards file of the project (default IntegrationTestBoards.json)
#   IT_BOARDS_FILE       - Output (default Build/IntegrationTestBoards.json)
#   IT_PROBE_RS          - probe-rs executable (default: IntegrationTesting_FindProbeRs)
################################################################################

cmake_minimum_required(VERSION 3.25)

include("${CMAKE_CURRENT_LIST_DIR}/IntegrationTesting_Probe.cmake")

#------------------------------------------------------------------------------#
# Selects the MCU of a probe from its candidates (MCUs with the same ID and
# flash size): the first candidate whose identification device probe-rs knows
# ("probe-rs chip info") - the integration test firmware of the board can be
# executed - or the first candidate when probe-rs knows none of them.
#
# MCU_VAR    [out]: Selected MCU
# PROBE_RS   [in]:  probe-rs executable
# CANDIDATES [in]:  Candidate MCUs (IT_MCU_<mcu>_DEVICE of
#                   IntegrationTesting_ReadMcuIdentification)
#------------------------------------------------------------------------------#
function(IntegrationTesting_SelectCandidate MCU_VAR PROBE_RS CANDIDATES)

    list(GET CANDIDATES 0 SELECTED)
    list(LENGTH CANDIDATES CANDIDATES_CNT)

    if(CANDIDATES_CNT GREATER 1)
        foreach(CANDIDATE IN LISTS CANDIDATES)

            if(NOT IT_MCU_${CANDIDATE}_DEVICE)
                continue()
            endif()

            execute_process(COMMAND "${PROBE_RS}" chip info "${IT_MCU_${CANDIDATE}_DEVICE}"
                            RESULT_VARIABLE CHIP_RESULT
                            OUTPUT_QUIET
                            ERROR_QUIET)

            if(CHIP_RESULT EQUAL 0)
                set(SELECTED "${CANDIDATE}")
                break()
            endif()

        endforeach()
    endif()

    set(${MCU_VAR} "${SELECTED}" PARENT_SCOPE)

endfunction(IntegrationTesting_SelectCandidate)

#------------------------------------------------------------------------------#
# Detects connected boards and writes the boards file of connected boards.
#
# PROJECT_DIR       [in]: Project root folder (CMakePresets.json)
# MCU_PRESETS_FILE  [in]: Ral presets with MCU identification
# OVERRIDE_FILE     [in]: Boards file of the project (may not exist)
# OUT_FILE          [in]: Boards file of connected boards
#------------------------------------------------------------------------------#
function(IntegrationTesting_DetectBoards PROJECT_DIR MCU_PRESETS_FILE OVERRIDE_FILE OUT_FILE)

    IntegrationTesting_FindProbeRs(IT_PROBE_RS "${PROJECT_DIR}")

    if(NOT IT_PROBE_RS)
        IntegrationTesting_InstallProbeRs(IT_PROBE_RS "${PROJECT_DIR}")
    endif()

    if(NOT IT_PROBE_RS)
        message(FATAL_ERROR "probe-rs not found - configure an integration test preset (artifact 'probe-rs') "
                            "or pass -DIT_PROBE_RS=<path>.")
    endif()

    # Integration test presets of the project
    set(PROJECT_PRESETS_FILE "${PROJECT_DIR}/CMakePresets.json")

    if(NOT EXISTS "${PROJECT_PRESETS_FILE}")
        message(FATAL_ERROR "${PROJECT_PRESETS_FILE} not found - execute the script from the project root folder.")
    endif()

    file(READ "${PROJECT_PRESETS_FILE}" PROJECT_PRESETS)
    string(JSON PRESETS_CNT ERROR_VARIABLE PRESETS_ERROR LENGTH "${PROJECT_PRESETS}" configurePresets)

    set(IT_PRESETS "")
    if(NOT PRESETS_ERROR AND PRESETS_CNT GREATER 0)
        math(EXPR PRESETS_LAST "${PRESETS_CNT} - 1")
        foreach(PRESET_IDX RANGE ${PRESETS_LAST})
            string(JSON PRESET_NAME GET "${PROJECT_PRESETS}" configurePresets ${PRESET_IDX} name)
            if(PRESET_NAME MATCHES "_IntegrationTest$")
                list(APPEND IT_PRESETS "${PRESET_NAME}")
            endif()
        endforeach()
    endif()

    # MCUs with identification and integration test preset
    IntegrationTesting_ReadMcuIdentification(ALL_MCUS "${MCU_PRESETS_FILE}")

    set(MCUS "")
    foreach(MCU IN LISTS ALL_MCUS)
        if("${MCU}_IntegrationTest" IN_LIST IT_PRESETS)
            list(APPEND MCUS "${MCU}")
        endif()
    endforeach()

    if(NOT MCUS)
        message(WARNING "No MCU identification for integration test presets of the project in ${MCU_PRESETS_FILE} - "
                        "boards are detected only by probes of ${OVERRIDE_FILE}.")
    endif()

    # Connected probes and their MCUs
    IntegrationTesting_ListProbes(PROBES)

    set(PROBE_IDX 0)
    foreach(PROBE IN LISTS PROBES)
        IntegrationTesting_IdentifyProbe(PROBE_${PROBE_IDX}_MCUS PROBE_${PROBE_IDX}_TEXT "${PROBE}" "${MCUS}")
        set(PROBE_${PROBE_IDX}_BOARD "")
        math(EXPR PROBE_IDX "${PROBE_IDX} + 1")
    endforeach()
    list(LENGTH PROBES PROBES_CNT)

    # Boards of the project (override)
    set(BOARDS "")

    if(EXISTS "${OVERRIDE_FILE}")
        file(READ "${OVERRIDE_FILE}" OVERRIDE_CONTENT)
        string(JSON OVERRIDE_CNT ERROR_VARIABLE OVERRIDE_ERROR LENGTH "${OVERRIDE_CONTENT}" boards)

        if(OVERRIDE_ERROR)
            message(WARNING "${OVERRIDE_FILE}: object \"boards\" not found - ignored.")
            set(OVERRIDE_CNT 0)
        endif()

        # Boards with probes first, then boards selected by MCU of the probe
        foreach(PASS IN ITEMS PROBES MCU)
            if(OVERRIDE_CNT EQUAL 0)
                break()
            endif()

            math(EXPR OVERRIDE_LAST "${OVERRIDE_CNT} - 1")
            foreach(BOARD_IDX RANGE ${OVERRIDE_LAST})

                string(JSON BOARD MEMBER "${OVERRIDE_CONTENT}" boards ${BOARD_IDX})
                string(JSON PRESET ERROR_VARIABLE PRESET_ERROR GET "${OVERRIDE_CONTENT}" boards ${BOARD} preset)
                string(JSON BOARD_PROBES_CNT ERROR_VARIABLE BOARD_PROBES_ERROR LENGTH "${OVERRIDE_CONTENT}" boards ${BOARD} probes)

                if(PRESET_ERROR)
                    if(PASS STREQUAL "PROBES")
                        message(WARNING "Board ${BOARD} has no \"preset\" in ${OVERRIDE_FILE} - skipped.")
                    endif()
                    continue()
                endif()

                if(BOARD_PROBES_ERROR)
                    set(BOARD_PROBES_CNT 0)
                endif()

                if(PASS STREQUAL "PROBES" AND BOARD_PROBES_CNT EQUAL 0)
                    continue()
                elseif(PASS STREQUAL "MCU" AND BOARD_PROBES_CNT GREATER 0)
                    continue()
                endif()

                set(BOARD_PROBES "")
                if(BOARD_PROBES_CNT GREATER 0)
                    math(EXPR BOARD_PROBES_LAST "${BOARD_PROBES_CNT} - 1")
                    foreach(BOARD_PROBE_IDX RANGE ${BOARD_PROBES_LAST})
                        string(JSON BOARD_PROBE GET "${OVERRIDE_CONTENT}" boards ${BOARD} probes ${BOARD_PROBE_IDX})
                        list(APPEND BOARD_PROBES "${BOARD_PROBE}")
                    endforeach()
                endif()

                string(REGEX REPLACE "_IntegrationTest$" "" BOARD_MCU "${PRESET}")

                set(PROBE_IDX 0)
                foreach(PROBE IN LISTS PROBES)
                    if(NOT PROBE_${PROBE_IDX}_BOARD)
                        set(IS_BOARD_PROBE FALSE)

                        if(PASS STREQUAL "PROBES")
                            foreach(BOARD_PROBE IN LISTS BOARD_PROBES)
                                if(PROBE STREQUAL BOARD_PROBE OR PROBE MATCHES ":${BOARD_PROBE}$")
                                    set(IS_BOARD_PROBE TRUE)
                                endif()
                            endforeach()
                        elseif("${BOARD_MCU}" IN_LIST PROBE_${PROBE_IDX}_MCUS)
                            set(IS_BOARD_PROBE TRUE)
                        endif()

                        if(IS_BOARD_PROBE)
                            set(PROBE_${PROBE_IDX}_BOARD "${BOARD}")
                            if(NOT "${BOARD}" IN_LIST BOARDS)
                                list(APPEND BOARDS "${BOARD}")
                                set(BOARD_${BOARD}_PRESET "${PRESET}")
                                string(JSON BOARD_${BOARD}_CACHE ERROR_VARIABLE CACHE_ERROR
                                       GET "${OVERRIDE_CONTENT}" boards ${BOARD} cacheVariables)
                                if(CACHE_ERROR)
                                    set(BOARD_${BOARD}_CACHE "")
                                endif()
                                set(BOARD_${BOARD}_PROBES "")
                            endif()
                            list(APPEND BOARD_${BOARD}_PROBES "${PROBE}")
                        endif()
                    endif()
                    math(EXPR PROBE_IDX "${PROBE_IDX} + 1")
                endforeach()

            endforeach()
        endforeach()
    endif()

    # Other identified probes - board named by the MCU
    set(NOT_IDENTIFIED "")
    set(PROBE_IDX 0)
    foreach(PROBE IN LISTS PROBES)
        if(NOT PROBE_${PROBE_IDX}_BOARD)
            if(PROBE_${PROBE_IDX}_MCUS)
                IntegrationTesting_SelectCandidate(BOARD "${IT_PROBE_RS}" "${PROBE_${PROBE_IDX}_MCUS}")
                list(LENGTH PROBE_${PROBE_IDX}_MCUS MCUS_CNT)

                if(MCUS_CNT GREATER 1)
                    list(JOIN PROBE_${PROBE_IDX}_MCUS ", " CANDIDATES_TEXT)
                    message(WARNING "Probe ${PROBE} (${PROBE_${PROBE_IDX}_TEXT}) matches more MCUs: ${CANDIDATES_TEXT} - "
                                    "${BOARD} is used (first one known by probe-rs). Define the board (preset) in ${OVERRIDE_FILE}.")
                endif()

                set(PROBE_${PROBE_IDX}_BOARD "${BOARD}")
                if(NOT "${BOARD}" IN_LIST BOARDS)
                    list(APPEND BOARDS "${BOARD}")
                    set(BOARD_${BOARD}_PRESET "${BOARD}_IntegrationTest")
                    set(BOARD_${BOARD}_CACHE  "")
                    set(BOARD_${BOARD}_PROBES "")
                endif()
                list(APPEND BOARD_${BOARD}_PROBES "${PROBE}")
            else()
                list(APPEND NOT_IDENTIFIED "${PROBE} (${PROBE_${PROBE_IDX}_TEXT})")
            endif()
        endif()
        math(EXPR PROBE_IDX "${PROBE_IDX} + 1")
    endforeach()

    # Boards file of connected boards
    set(OUT_JSON "{ \"boards\": {} }")

    message("Connected boards:")

    if(NOT BOARDS)
        message("  none")
    endif()

    foreach(BOARD IN LISTS BOARDS)

        set(PROBES_JSON "")
        set(PROBES_TEXT "")
        foreach(PROBE IN LISTS BOARD_${BOARD}_PROBES)
            list(APPEND PROBES_JSON "\"${PROBE}\"")
            list(FIND PROBES "${PROBE}" PROBE_IDX)
            list(APPEND PROBES_TEXT "${PROBE} (${PROBE_${PROBE_IDX}_TEXT})")
        endforeach()
        list(JOIN PROBES_JSON ", " PROBES_JSON)
        list(JOIN PROBES_TEXT ", " PROBES_TEXT)

        string(JSON OUT_JSON SET "${OUT_JSON}" boards "${BOARD}" "{}")
        string(JSON OUT_JSON SET "${OUT_JSON}" boards "${BOARD}" preset "\"${BOARD_${BOARD}_PRESET}\"")
        string(JSON OUT_JSON SET "${OUT_JSON}" boards "${BOARD}" probes "[ ${PROBES_JSON} ]")
        if(BOARD_${BOARD}_CACHE)
            string(JSON OUT_JSON SET "${OUT_JSON}" boards "${BOARD}" cacheVariables "${BOARD_${BOARD}_CACHE}")
        endif()

        if(NOT "${BOARD_${BOARD}_PRESET}" IN_LIST IT_PRESETS)
            message(WARNING "Preset ${BOARD_${BOARD}_PRESET} of board ${BOARD} is not in ${PROJECT_PRESETS_FILE}.")
        endif()

        message("  ${BOARD} (${BOARD_${BOARD}_PRESET}): ${PROBES_TEXT}")

    endforeach()

    if(NOT_IDENTIFIED)
        message("Probes without identified MCU (not used):")
        foreach(PROBE_TEXT IN LISTS NOT_IDENTIFIED)
            message("  ${PROBE_TEXT}")
        endforeach()
    endif()

    if(PROBES_CNT EQUAL 0)
        message("No debug probe is connected.")
    endif()

    get_filename_component(OUT_DIR "${OUT_FILE}" DIRECTORY)
    file(MAKE_DIRECTORY "${OUT_DIR}")
    file(WRITE "${OUT_FILE}" "${OUT_JSON}\n")

endfunction(IntegrationTesting_DetectBoards)


#==============================================================================#
# Script mode
#==============================================================================#
if(CMAKE_SCRIPT_MODE_FILE AND CMAKE_SCRIPT_MODE_FILE STREQUAL CMAKE_CURRENT_LIST_FILE)

    set(IT_PROJECT_DIR "${CMAKE_SOURCE_DIR}")

    if(NOT IT_MCU_PRESETS_FILE)
        set(IT_MCU_PRESETS_FILE "${IT_PROJECT_DIR}/Bsp/Ral/RalPresets.json")
    endif()

    if(NOT IT_BOARDS_OVERRIDE)
        set(IT_BOARDS_OVERRIDE "${IT_PROJECT_DIR}/IntegrationTestBoards.json")
    endif()

    if(NOT IT_BOARDS_FILE)
        set(IT_BOARDS_FILE "${IT_PROJECT_DIR}/Build/IntegrationTestBoards.json")
    endif()

    IntegrationTesting_DetectBoards("${IT_PROJECT_DIR}" "${IT_MCU_PRESETS_FILE}" "${IT_BOARDS_OVERRIDE}" "${IT_BOARDS_FILE}")

endif()
