/**
 * \author Mr.Nobody
 * \file IntegrationTesting.h
 * \ingroup IntegrationTesting
 * \brief Integration testing on target - result mailbox and Unity output.
 *
 * Integration test firmware runs Unity tests on the target. Every test case runs
 * after system reset of the target - one test case per boot, the framework resets
 * the target after the test case and continues by the next one. Unity output and
 * state of the execution are stored in the result mailbox (\ref integrationTesting_Mailbox)
 * in RAM section ".noinit", which is not initialized by the startup code, so the
 * content is kept over system reset. Host reads the mailbox through debug probe.
 * The mailbox does not use any peripheral, so the tests do not depend on USART,
 * pins or clocks.
 *
 * The framework is independent of the target. Initialization, fault handlers
 * and system reset are implemented by the test set (IntegrationTesting_Target.h).
 * Faults passed by the test set to \ref IntegrationTesting_ReportFault are
 * reported as failure of the running test case and the execution continues by
 * the next test case.
 *
 * \note Only requirement on the target: linker section ".noinit" in RAM, which
 *       is not initialized by the startup code and kept over system reset.
 */

#ifndef INTEGRATIONTESTING_INTEGRATIONTESTING_H
#define INTEGRATIONTESTING_INTEGRATIONTESTING_H

#ifdef __cplusplus
 extern "C" {
#endif /* __cplusplus */

/* ============================= INCLUDES =================================== */
#include "stdint.h"                         /* Standard types                 */
/* ============================= TYPEDEFS =================================== */

/** \brief State of integration test execution stored in the mailbox */
typedef enum
{
    IT_STATE_RUNNING  = 0x52554E21u,        /**< Tests are executed ("RUN!")  */
    IT_STATE_FINISHED = 0x444F4E45u         /**< Tests are finished ("DONE")  */
}   integrationTesting_State_t;


/** \brief Origin of the test session stored in the mailbox */
typedef enum
{
    IT_SESSION_HOST  = 0x484F5354u,         /**< Started by host (\ref IT_MAILBOX_START written before reset) ("HOST") */
    IT_SESSION_LOCAL = 0x4C4F434Cu          /**< Started without host - power-on, debugger, lost mailbox ("LOCL")      */
}   integrationTesting_Session_t;


/** \brief Command written by host into the mailbox before reset of the MCU */
typedef enum
{
    IT_COMMAND_NONE  = 0x00000000u,         /**< No command                                                  */
    IT_COMMAND_ABORT = 0x41425254u          /**< Running test case is blocked, host aborted it ("ABRT")      */
}   integrationTesting_Command_t;


/** \brief Phase of the actual test case (evaluated after reset) */
typedef enum
{
    IT_CASE_IDLE           = 0x00000000u,   /**< No test case is executed                                    */
    IT_CASE_RUNNING        = 0x43415345u,   /**< Test case is executed, reset is not expected ("CASE")       */
    IT_CASE_RESET_EXPECTED = 0x52535445u    /**< Test case is executed, it expects reset of MCU ("RSTE")     */
}   integrationTesting_CasePhase_t;


/** \brief Stage of the test case - count of expected resets during the test case */
typedef uint32_t integrationTesting_Stage_t;


/** \brief Test function of Unity test case */
typedef void ( *integrationTesting_TestFunc_t )( void );


/** \brief Test case description (table generated by IntegrationTesting.cmake) */
typedef struct
{
    integrationTesting_TestFunc_t   Func;   /**< Test function                                */
    const char*                     Name;   /**< Name of the test function                    */
    uint32_t                        Line;   /**< Line of the test function in the test file   */
}   integrationTesting_TestCase_t;


/** \brief Register reported with fault (eg. PC, LR, CFSR) - chosen by the test set */
typedef struct
{
    const char*                     Name;   /**< Name of the register printed in the report   */
    uint32_t                        Value;  /**< Value of the register                        */
}   integrationTesting_FaultReg_t;


/**
 * \brief Result mailbox read by host (see IntegrationTesting_Run.cmake).
 *
 * \note Layout of the header (12 words) is part of the host interface.
 */
typedef struct
{
    volatile uint32_t                       Magic;      /**< \ref IT_MAILBOX_MAGIC when mailbox is valid, host writes \ref IT_MAILBOX_START */
    volatile integrationTesting_State_t     State;      /**< Test execution state                                           */
    volatile uint32_t                       Length;     /**< Count of characters stored in Output                           */
    volatile uint32_t                       Size;       /**< Size of Output buffer (overflow detection)                     */
    volatile integrationTesting_Session_t   Session;    /**< Origin of the test session                                     */
    volatile integrationTesting_Command_t   Command;    /**< Command of host (written before reset)                         */
    volatile uint32_t                       TestIndex;  /**< Index of the actual test case                                  */
    volatile uint32_t                       TestCount;  /**< Count of test cases of the firmware                            */
    volatile integrationTesting_Stage_t     TestStage;  /**< Stage of the actual test case                                  */
    volatile integrationTesting_CasePhase_t CasePhase;  /**< Phase of the actual test case                                  */
    volatile uint32_t                       Failures;   /**< Count of failed test cases                                     */
    volatile uint32_t                       Ignored;    /**< Count of ignored test cases                                    */
    volatile char                           Output[ IT_OUTPUT_SIZE ]; /**< Unity output (text)                                */
}   integrationTesting_Mailbox_t;

/* ========================= SYMBOLIC CONSTANTS ============================= */

/** Mailbox identification ("ITMB") */
#define IT_MAILBOX_MAGIC                    ( 0x49544D42u )

/** Request of host to start new test session, written into Magic ("ITST") */
#define IT_MAILBOX_START                    ( 0x49545354u )

/* ========================= EXPORTED MACROS ================================ */

/**
 * \brief Marks test of known (reported, not yet fixed) defect of the module.
 *
 * Same meaning as UT_KNOWN_DEFECT of unit tests. By default the test is
 * reported as ignored, with INTEGRATION_TEST_RUN_KNOWN_DEFECTS=ON it is executed.
 */
#if defined(IT_RUN_KNOWN_DEFECTS)
    #define IT_KNOWN_DEFECT( description )      do { } while( 0 )
#else
    #define IT_KNOWN_DEFECT( description )      TEST_IGNORE_MESSAGE( "KNOWN DEFECT: " description )
#endif

/* ========================= EXPORTED VARIABLES ============================= */

extern integrationTesting_Mailbox_t         integrationTesting_Mailbox;

/* Generated by IntegrationTesting.cmake (IT_<NAME>_Runner.c) */
extern const char                           integrationTesting_TestFile[];
extern const integrationTesting_TestCase_t  integrationTesting_TestCases[];
extern const uint32_t                       integrationTesting_TestCount;

/* ======================== EXPORTED FUNCTIONS ============================== */

void                        IntegrationTesting_Run              ( void );
void                        IntegrationTesting_ReportFault      ( const char* faultName, const integrationTesting_FaultReg_t* faultRegs, uint32_t faultRegCnt );

void                        IntegrationTesting_PutChar          ( int character );

integrationTesting_Stage_t  IntegrationTesting_Get_Stage        ( void );
void                        IntegrationTesting_Set_ResetExpected( void );

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* INTEGRATIONTESTING_INTEGRATIONTESTING_H */
