################################################################################
#
# VSCode project initialization CMake script.
#
# The project gets following VSCode configuration:
#
# Project_root/
# │
# ...
# └── .vscode
#     ├── tasks.json                (Build, clean rebuild, flash, unit tests,
#     │                              integration tests, detection of boards,
#     │                              Setup)
#     ├── launch.json               (probe-rs debugging of the MCU firmware and
#     │                              integration test firmwares, gdb debugging
#     │                              of unit tests)
#     ├── settings.json             (CMake Tools with project presets,
#     │                              IntelliSense, excludes - other settings of
#     │                              an existing file are kept)
#     ├── c_cpp_properties.json     (IntelliSense configuration from CMake Tools)
#     └── extensions.json           (Recommended extensions)
#
# Tasks select the MCU, build type, board and test set from lists and execute
# Build_Handler.cmake (same build and test flow as Setup options Build and
# Tests). Debug configurations are generated for the selected MCUs (default MCUs
# of the connected boards) - probe-rs
# chip of the MCU (board chip of IntegrationTestBoards.json, device of the MCU
# identification of the Ral presets or MCU name - the first one probe-rs
# knows), probe of the MCU from detection of connected boards and SVD file if
# found (project, STM32Cube packs - device family pack is installed by the
# STM32Cube extension if it is installed and the SVD file is missing).
#
# Generated files start with the comment VSCODE_GENERATED_MARK. Existing files
# without the mark (created by user or other tools) are kept as <file>.bak.
#
# User can execute initialization through this CMake script - generation is
# repeated after change of MCUs, boards or test sets of the project.
#
################################################################################

# Set path to system configuration file
get_filename_component(SYSTEM_CONFIG_FILE_PATH "${CMAKE_CURRENT_LIST_DIR}/../../SysConfig.cmake" REALPATH)

# Include file with system configuration values
include("${SYSTEM_CONFIG_FILE_PATH}")

# MCUs of the project presets, detection of connected boards
include("${CMAKE_CURRENT_LIST_DIR}/../Build_Handler/Build_Handler.cmake")

# probe-rs search, MCU identification of the Ral presets
include("${CMAKE_CURRENT_LIST_DIR}/../../IntegrationTesting/IntegrationTesting_Probe.cmake")

#==============================================================================#
# Global variables
#==============================================================================#

# Read project root folder path
SysConfig_Get_ProjectRootPath(PROJECT_ROOT_PATH)

set(VSCODE_DIR                  "${PROJECT_ROOT_PATH}/.vscode")

# Mark of the generated files (first line)
set(VSCODE_GENERATED_MARK       "// Generated by EmBi_Platform Setup (VSCode project initialization).")

# Scripts executed by tasks (relative to project root)
file(RELATIVE_PATH VSCODE_BUILD_HANDLER "${PROJECT_ROOT_PATH}"
     "${CMAKE_CURRENT_LIST_DIR}/../Build_Handler/Build_Handler.cmake")
file(RELATIVE_PATH VSCODE_HANDLER "${PROJECT_ROOT_PATH}" "${CMAKE_CURRENT_LIST_FILE}")
file(RELATIVE_PATH VSCODE_SETUP_DIR "${PROJECT_ROOT_PATH}" "${CMAKE_CURRENT_LIST_DIR}/../../..")

# Ral presets with MCU identification
set(VSCODE_RAL_PRESETS_FILE     "${PROJECT_ROOT_PATH}/Bsp/Ral/RalPresets.json")

# Boards of the project (override of detected boards)
set(VSCODE_PROJECT_BOARDS_FILE  "${PROJECT_ROOT_PATH}/IntegrationTestBoards.json")

# Folders not searched for tests
set(VSCODE_EXCLUDED_DIRS        "Build;EmBi_Platform;STM32CubeIDE;.git;.vscode;.settings")

# Recommended extensions (Serial Monitor - firmware output over ST-LINK VCP)
set(VSCODE_EXTENSIONS           "ms-vscode.cmake-tools;ms-vscode.cpptools;probe-rs.probe-rs-debugger;ms-vscode.vscode-serial-monitor")

# Max length of one line arrays of strings
set(VSCODE_LINE_LENGTH          100)

# gcc problem matcher with file paths of the compiler (absolute or relative)
set(VSCODE_PROBLEM_MATCHER      "{ \"base\": \"$gcc\", \"fileLocation\": [ \"autoDetect\", \"\${workspaceFolder}\" ] }")


#==============================================================================#
# Functions
#==============================================================================#

# ------------------------------------------------------------------------------
# Function: Prj_VSCode_JsonString
# Description: JSON string of the text.
#
# OUT_JSON [out]: JSON string.
# IN_TEXT  [in]:  Text.
# ------------------------------------------------------------------------------
function(Prj_VSCode_JsonString OUT_JSON IN_TEXT)

    string(REPLACE "\\" "\\\\" TEXT "${IN_TEXT}")
    string(REPLACE "\"" "\\\"" TEXT "${TEXT}")

    set(${OUT_JSON} "\"${TEXT}\"" PARENT_SCOPE)
endfunction()


# ------------------------------------------------------------------------------
# Function: Prj_VSCode_JsonStringArray
# Description: JSON array of strings - one line, multi-line if the line is
#              longer than VSCODE_LINE_LENGTH.
#
# OUT_JSON [out]: JSON array.
# ARGN     [in]:  Strings.
# ------------------------------------------------------------------------------
function(Prj_VSCode_JsonStringArray OUT_JSON)

    set(ITEMS "")

    foreach(TEXT IN LISTS ARGN)
        Prj_VSCode_JsonString(ITEM "${TEXT}")
        list(APPEND ITEMS "${ITEM}")
    endforeach()

    list(JOIN ITEMS ", " LINE)
    string(LENGTH "${LINE}" LINE_LENGTH)

    if(NOT ITEMS)
        set(ARRAY "[]")
    elseif(LINE_LENGTH GREATER VSCODE_LINE_LENGTH)
        Prj_VSCode_JsonArray(ARRAY ${ITEMS})
    else()
        set(ARRAY "[ ${LINE} ]")
    endif()

    set(${OUT_JSON} "${ARRAY}" PARENT_SCOPE)
endfunction()


# ------------------------------------------------------------------------------
# Function: Prj_VSCode_JsonObject
# Description: Multi-line JSON object, nested values are indented.
#
# OUT_JSON [out]: JSON object.
# ARGN     [in]:  Pairs of member name and JSON value (values without ';').
# ------------------------------------------------------------------------------
function(Prj_VSCode_JsonObject OUT_JSON)

    set(MEMBERS "")

    while(ARGN)
        list(POP_FRONT ARGN NAME VALUE)
        Prj_VSCode_JsonString(NAME "${NAME}")
        string(REPLACE "\n" "\n    " VALUE "${VALUE}")
        list(APPEND MEMBERS "    ${NAME}: ${VALUE}")
    endwhile()

    if(MEMBERS)
        list(JOIN MEMBERS ",\n" MEMBERS)
        set(${OUT_JSON} "{\n${MEMBERS}\n}" PARENT_SCOPE)
    else()
        set(${OUT_JSON} "{}" PARENT_SCOPE)
    endif()
endfunction()


# ------------------------------------------------------------------------------
# Function: Prj_VSCode_JsonArray
# Description: Multi-line JSON array, nested values are indented.
#
# OUT_JSON [out]: JSON array.
# ARGN     [in]:  JSON values (without ';').
# ------------------------------------------------------------------------------
function(Prj_VSCode_JsonArray OUT_JSON)

    set(ITEMS "")

    foreach(VALUE IN LISTS ARGN)
        string(REPLACE "\n" "\n    " VALUE "${VALUE}")
        list(APPEND ITEMS "    ${VALUE}")
    endforeach()

    if(ITEMS)
        list(JOIN ITEMS ",\n" ITEMS)
        set(${OUT_JSON} "[\n${ITEMS}\n]" PARENT_SCOPE)
    else()
        set(${OUT_JSON} "[]" PARENT_SCOPE)
    endif()
endfunction()


# ------------------------------------------------------------------------------
# Function: Prj_VSCode_WriteFile
# Description: Writes generated file of the .vscode folder. Existing file
#              without the generated mark is kept as <file>.bak.
#
# IN_NAME    [in]: File name.
# IN_CONTENT [in]: Content without the generated mark.
# ------------------------------------------------------------------------------
function(Prj_VSCode_WriteFile IN_NAME IN_CONTENT)

    set(FILE_PATH "${VSCODE_DIR}/${IN_NAME}")
    set(CONTENT   "${VSCODE_GENERATED_MARK}\n${IN_CONTENT}\n")

    if(EXISTS "${FILE_PATH}")

        file(READ "${FILE_PATH}" OLD_CONTENT)
        string(FIND "${OLD_CONTENT}" "${VSCODE_GENERATED_MARK}" MARK_POS)

        if(NOT MARK_POS EQUAL 0)
            file(COPY_FILE "${FILE_PATH}" "${FILE_PATH}.bak")
            message("Existing ${IN_NAME} kept as ${IN_NAME}.bak")
        endif()

    endif()

    file(WRITE "${FILE_PATH}" "${CONTENT}")
    message("Generated: .vscode/${IN_NAME}")
endfunction()


# ------------------------------------------------------------------------------
# Function: Prj_VSCode_GetFirmwareName
# Description: File name of the project firmware (project name of the root
#              CMakeLists.txt, "<name>_${CMAKE_BUILD_TYPE}" + ".elf").
#
# IN_BUILD_TYPE [in]:  Debug or Release.
# OUT_NAME      [out]: File name of the firmware.
# ------------------------------------------------------------------------------
function(Prj_VSCode_GetFirmwareName IN_BUILD_TYPE OUT_NAME)

    set(PROJECT_NAME_TEXT "")

    if(EXISTS "${PROJECT_ROOT_PATH}/CMakeLists.txt")
        file(STRINGS "${PROJECT_ROOT_PATH}/CMakeLists.txt" NAME_LINE REGEX "^[ \t]*set\\(PROJECT_NAME[ \t]+\"[^\"]+\"")
        if(NAME_LINE MATCHES "set\\(PROJECT_NAME[ \t]+\"([^\"]+)\"")
            set(PROJECT_NAME_TEXT "${CMAKE_MATCH_1}")
        endif()
    endif()

    if(PROJECT_NAME_TEXT STREQUAL "")
        message(WARNING "PROJECT_NAME not found in ${PROJECT_ROOT_PATH}/CMakeLists.txt - firmware name Project_Template_<build type> is used.")
        set(PROJECT_NAME_TEXT "Project_Template_\${CMAKE_BUILD_TYPE}")
    endif()

    string(REPLACE "\${CMAKE_BUILD_TYPE}" "${IN_BUILD_TYPE}" PROJECT_NAME_TEXT "${PROJECT_NAME_TEXT}")

    set(${OUT_NAME} "${PROJECT_NAME_TEXT}.elf" PARENT_SCOPE)
endfunction()


# ------------------------------------------------------------------------------
# Function: Prj_VSCode_GetTestFirmwares
# Description: Test executables of the project - test sets registered in
#              <module>/Tests/<UnitTests|IntegrationTests>/CMakeLists.txt
#              (UnitTesting_Add_Test / IntegrationTesting_Add_Test NAME). Paths
#              are relative to the tests folder of the build
#              (Build/<preset>/<UnitTests|IntegrationTests>).
#
# IN_TESTS_DIR [in]:  UnitTests or IntegrationTests.
# OUT_LIST     [out]: Sorted list of <module path>/Tests/<dir>/<UT|IT>_<NAME><suffix>.
# ------------------------------------------------------------------------------
function(Prj_VSCode_GetTestFirmwares IN_TESTS_DIR OUT_LIST)

    if("${IN_TESTS_DIR}" STREQUAL "UnitTests")
        set(PREFIX "UT_")
        set(SUFFIX "")
        if(CMAKE_HOST_WIN32)
            set(SUFFIX ".exe")
        endif()
    else()
        set(PREFIX "IT_")
        set(SUFFIX ".elf")
    endif()

    file(GLOB TOP_DIRS LIST_DIRECTORIES true RELATIVE "${PROJECT_ROOT_PATH}" "${PROJECT_ROOT_PATH}/*")

    set(FIRMWARES "")

    foreach(TOP_DIR IN LISTS TOP_DIRS)

        if(NOT IS_DIRECTORY "${PROJECT_ROOT_PATH}/${TOP_DIR}" OR "${TOP_DIR}" IN_LIST VSCODE_EXCLUDED_DIRS)
            continue()
        endif()

        file(GLOB_RECURSE TEST_LISTS RELATIVE "${PROJECT_ROOT_PATH}" "${PROJECT_ROOT_PATH}/${TOP_DIR}/CMakeLists.txt")
        list(FILTER TEST_LISTS INCLUDE REGEX "/Tests/${IN_TESTS_DIR}/CMakeLists\\.txt$")

        foreach(TEST_LIST IN LISTS TEST_LISTS)

            file(READ "${PROJECT_ROOT_PATH}/${TEST_LIST}" TEST_CONTENT)
            string(REGEX MATCHALL "_Add_Test\\([ \t\r\n]*NAME[ \t]+[A-Za-z0-9_]+" TESTS "${TEST_CONTENT}")
            get_filename_component(TEST_DIR "${TEST_LIST}" DIRECTORY)

            foreach(TEST IN LISTS TESTS)
                string(REGEX REPLACE "^.*NAME[ \t]+" "" TEST_NAME "${TEST}")
                list(APPEND FIRMWARES "${TEST_DIR}/${PREFIX}${TEST_NAME}${SUFFIX}")
            endforeach()

        endforeach()

    endforeach()

    list(REMOVE_DUPLICATES FIRMWARES)
    list(SORT FIRMWARES)

    set(${OUT_LIST} "${FIRMWARES}" PARENT_SCOPE)
endfunction()


# ------------------------------------------------------------------------------
# Function: Prj_VSCode_GetProjectBoards
# Description: Boards of the project boards file (IntegrationTestBoards.json).
#
# OUT_BOARD_LIST [out]: List of boards.
# ------------------------------------------------------------------------------
function(Prj_VSCode_GetProjectBoards OUT_BOARD_LIST)

    set(BOARD_LIST "")

    if(EXISTS "${VSCODE_PROJECT_BOARDS_FILE}")

        file(READ "${VSCODE_PROJECT_BOARDS_FILE}" BOARDS_CONTENT)
        string(JSON BOARDS_CNT ERROR_VARIABLE BOARDS_ERROR LENGTH "${BOARDS_CONTENT}" boards)

        if(NOT BOARDS_ERROR AND BOARDS_CNT GREATER 0)
            math(EXPR BOARDS_LAST "${BOARDS_CNT} - 1")
            foreach(BOARD_IDX RANGE ${BOARDS_LAST})
                string(JSON BOARD MEMBER "${BOARDS_CONTENT}" boards ${BOARD_IDX})
                list(APPEND BOARD_LIST "${BOARD}")
            endforeach()
        endif()

    endif()

    set(${OUT_BOARD_LIST} "${BOARD_LIST}" PARENT_SCOPE)
endfunction()


# ------------------------------------------------------------------------------
# Function: Prj_VSCode_GetBoardValue
# Description: Value of the first board of the boards file with the integration
#              test preset of the MCU.
#
# IN_BOARDS_FILE [in]:  Boards file.
# IN_MCU         [in]:  MCU.
# OUT_VALUE      [out]: Value ("" if not found).
# ARGN           [in]:  Path of the value in the board object.
# ------------------------------------------------------------------------------
function(Prj_VSCode_GetBoardValue IN_BOARDS_FILE IN_MCU OUT_VALUE)

    set(VALUE "")

    if(EXISTS "${IN_BOARDS_FILE}")

        file(READ "${IN_BOARDS_FILE}" BOARDS_CONTENT)
        string(JSON BOARDS_CNT ERROR_VARIABLE BOARDS_ERROR LENGTH "${BOARDS_CONTENT}" boards)

        if(NOT BOARDS_ERROR AND BOARDS_CNT GREATER 0)

            math(EXPR BOARDS_LAST "${BOARDS_CNT} - 1")

            foreach(BOARD_IDX RANGE ${BOARDS_LAST})

                string(JSON BOARD MEMBER "${BOARDS_CONTENT}" boards ${BOARD_IDX})
                string(JSON PRESET ERROR_VARIABLE PRESET_ERROR GET "${BOARDS_CONTENT}" boards "${BOARD}" preset)

                if(NOT PRESET_ERROR AND "${PRESET}" STREQUAL "${IN_MCU}_IntegrationTest")
                    string(JSON BOARD_VALUE ERROR_VARIABLE VALUE_ERROR GET "${BOARDS_CONTENT}" boards "${BOARD}" ${ARGN})
                    if(NOT VALUE_ERROR AND NOT "${BOARD_VALUE}" STREQUAL "")
                        set(VALUE "${BOARD_VALUE}")
                        break()
                    endif()
                endif()

            endforeach()

        endif()

    endif()

    set(${OUT_VALUE} "${VALUE}" PARENT_SCOPE)
endfunction()


# ------------------------------------------------------------------------------
# Function: Prj_VSCode_GetChip
# Description: probe-rs chip of the MCU - board chip of the project boards file,
#              device of the MCU identification or MCU name, the first one
#              probe-rs knows (the first candidate without probe-rs).
#
# IN_MCU   [in]:  MCU.
# OUT_CHIP [out]: probe-rs chip.
# ------------------------------------------------------------------------------
function(Prj_VSCode_GetChip IN_MCU OUT_CHIP)

    Prj_VSCode_GetBoardValue("${VSCODE_PROJECT_BOARDS_FILE}" "${IN_MCU}" BOARD_CHIP cacheVariables INTEGRATION_TEST_PROBE_RS_CHIP)

    set(CANDIDATES "")

    foreach(CANDIDATE IN ITEMS "${BOARD_CHIP}" "${IT_MCU_${IN_MCU}_DEVICE}" "${IN_MCU}")
        if(NOT "${CANDIDATE}" STREQUAL "")
            list(APPEND CANDIDATES "${CANDIDATE}")
        endif()
    endforeach()

    list(GET CANDIDATES 0 CHIP)

    if(VSCODE_PROBE_RS)

        set(CHIP_FOUND FALSE)

        foreach(CANDIDATE IN LISTS CANDIDATES)
            execute_process(COMMAND "${VSCODE_PROBE_RS}" chip info "${CANDIDATE}"
                            RESULT_VARIABLE CHIP_RESULT OUTPUT_QUIET ERROR_QUIET)
            if(CHIP_RESULT EQUAL 0)
                set(CHIP "${CANDIDATE}")
                set(CHIP_FOUND TRUE)
                break()
            endif()
        endforeach()

        if(NOT CHIP_FOUND)
            list(JOIN CANDIDATES ", " CANDIDATES_TEXT)
            message(WARNING "probe-rs knows no chip of ${IN_MCU} (${CANDIDATES_TEXT}) - set \"chip\" in launch.json.")
        endif()

    endif()

    set(${OUT_CHIP} "${CHIP}" PARENT_SCOPE)
endfunction()


# ------------------------------------------------------------------------------
# Function: Prj_VSCode_GetProbe
# Description: Probe of the MCU - the first probe of the first connected board
#              with the MCU (Build/IntegrationTestBoards.json of the last
#              detection).
#
# IN_MCU    [in]:  MCU.
# OUT_PROBE [out]: probe-rs selector VID:PID[:SN] ("" if no board is connected).
# ------------------------------------------------------------------------------
function(Prj_VSCode_GetProbe IN_MCU OUT_PROBE)

    Prj_VSCode_GetBoardValue("${BUILD_HANDLER_BOARDS_FILE}" "${IN_MCU}" PROBE probes 0)

    set(${OUT_PROBE} "${PROBE}" PARENT_SCOPE)
endfunction()


# ------------------------------------------------------------------------------
# Function: Prj_VSCode_FindSvd
# Description: SVD file of the MCU - the longest SVD file name the MCU starts
#              with ('x' of the name matches any character) from
#              VSCODE_SVD_FILES.
#
# IN_MCU  [in]:  MCU.
# OUT_SVD [out]: SVD file ("" if not found).
# ------------------------------------------------------------------------------
function(Prj_VSCode_FindSvd IN_MCU OUT_SVD)

    string(TOUPPER "${IN_MCU}" MCU_UPPER)

    set(SVD "")
    set(SVD_LENGTH 0)

    foreach(SVD_FILE IN LISTS VSCODE_SVD_FILES)

        get_filename_component(SVD_NAME "${SVD_FILE}" NAME_WE)
        string(REGEX REPLACE "x" "." SVD_REGEX "${SVD_NAME}")
        string(TOUPPER "${SVD_REGEX}" SVD_REGEX)
        string(LENGTH "${SVD_NAME}" NAME_LENGTH)

        if(NAME_LENGTH GREATER SVD_LENGTH AND "${MCU_UPPER}" MATCHES "^${SVD_REGEX}")
            set(SVD "${SVD_FILE}")
            set(SVD_LENGTH ${NAME_LENGTH})
        endif()

    endforeach()

    set(${OUT_SVD} "${SVD}" PARENT_SCOPE)
endfunction()


# ------------------------------------------------------------------------------
# Function: Prj_VSCode_FindTools
# Description: Finds tools of the debug configurations (parent scope):
#              VSCODE_PROBE_RS (probe-rs, "" if not found), VSCODE_GDB (host
#              gdb of unit tests - gcc artifact or PATH) and VSCODE_SVD_FILES
#              (SVD files of the project and STM32Cube packs).
# ------------------------------------------------------------------------------
function(Prj_VSCode_FindTools)

    IntegrationTesting_FindProbeRs(PROBE_RS "${PROJECT_ROOT_PATH}")

    # Host gdb - gcc artifact of the unit tests (Windows), PATH
    set(GDB "")

    if(EXISTS "${PROJECT_ROOT_PATH}/ArtifactsConfig.txt")
        file(STRINGS "${PROJECT_ROOT_PATH}/ArtifactsConfig.txt" CACHE_LINE REGEX "^ARTIFACTS_HANDLER_CACHE_PATH=")
        string(REGEX REPLACE "^ARTIFACTS_HANDLER_CACHE_PATH=" "" ARTIFACTS_CACHE "${CACHE_LINE}")
        file(TO_CMAKE_PATH "${ARTIFACTS_CACHE}" ARTIFACTS_CACHE)

        if(ARTIFACTS_CACHE)
            file(GLOB CACHED_GDB "${ARTIFACTS_CACHE}/gcc/Bin/*/mingw64/bin/gdb.exe")
            list(SORT CACHED_GDB COMPARE NATURAL ORDER DESCENDING)
            if(CACHED_GDB)
                list(GET CACHED_GDB 0 GDB)
            endif()
        endif()
    endif()

    if(NOT GDB)
        find_program(VSCODE_GDB_FOUND NAMES gdb NO_CACHE)
        if(VSCODE_GDB_FOUND)
            set(GDB "${VSCODE_GDB_FOUND}")
        else()
            set(GDB "gdb")
        endif()
    endif()

    # SVD files - project (Bsp, documents) and STM32Cube packs of VSCode extension
    set(SVD_GLOBS "${PROJECT_ROOT_PATH}/Bsp/*.svd" "${PROJECT_ROOT_PATH}/EmBi_Platform/Docs/*.svd")

    if(DEFINED ENV{LOCALAPPDATA})
        file(TO_CMAKE_PATH "$ENV{LOCALAPPDATA}" LOCAL_APP_DATA)
        list(APPEND SVD_GLOBS "${LOCAL_APP_DATA}/stm32cube/packs/*.svd")
    endif()

    if(DEFINED ENV{HOME})
        file(TO_CMAKE_PATH "$ENV{HOME}" HOME_DIR)
        list(APPEND SVD_GLOBS "${HOME_DIR}/.local/share/stm32cube/packs/*.svd")
    endif()

    file(GLOB_RECURSE SVD_FILES ${SVD_GLOBS})

    set(VSCODE_PROBE_RS  "${PROBE_RS}"  PARENT_SCOPE)
    set(VSCODE_GDB       "${GDB}"       PARENT_SCOPE)
    set(VSCODE_SVD_FILES "${SVD_FILES}" PARENT_SCOPE)
endfunction()


# ------------------------------------------------------------------------------
# Function: Prj_VSCode_InstallSvdPacks
# Description: Installs device family packs (STMicroelectronics.stm32<family>xx_dfp)
#              of the MCUs without SVD file by the STM32Cube VSCode extension
#              (cube pack install) and adds SVD files of the CMSIS pack root to
#              VSCODE_SVD_FILES (parent scope). Without the extension nothing is
#              installed.
#
# IN_MCU_LIST [in]: MCUs of the debug configurations.
# ------------------------------------------------------------------------------
function(Prj_VSCode_InstallSvdPacks IN_MCU_LIST)

    set(PACKS "")

    foreach(MCU IN LISTS IN_MCU_LIST)
        Prj_VSCode_FindSvd(${MCU} SVD)
        if(NOT SVD AND "${MCU}" MATCHES "^(STM32[A-Z][0-9A-Z])")
            string(TOLOWER "${CMAKE_MATCH_1}" FAMILY)
            list(APPEND PACKS "STMicroelectronics.${FAMILY}xx_dfp")
        endif()
    endforeach()

    if(NOT PACKS)
        return()
    endif()

    list(REMOVE_DUPLICATES PACKS)

    # cube CLI of the STM32Cube extension - PATH, extension folder
    find_program(VSCODE_CUBE_FOUND NAMES cube NO_CACHE)
    set(CUBE "${VSCODE_CUBE_FOUND}")

    if(NOT CUBE)
        foreach(HOME_VAR IN ITEMS USERPROFILE HOME)
            if(DEFINED ENV{${HOME_VAR}})
                file(TO_CMAKE_PATH "$ENV{${HOME_VAR}}" HOME_DIR)
                file(GLOB CUBE_CANDIDATES
                     "${HOME_DIR}/.vscode/extensions/stmicroelectronics.stm32cube-ide-core-*/resources/binaries/*/*/cube.exe"
                     "${HOME_DIR}/.vscode/extensions/stmicroelectronics.stm32cube-ide-core-*/resources/binaries/*/*/cube")
                list(SORT CUBE_CANDIDATES COMPARE NATURAL ORDER DESCENDING)
                if(CUBE_CANDIDATES)
                    list(GET CUBE_CANDIDATES 0 CUBE)
                    break()
                endif()
            endif()
        endforeach()
    endif()

    if(NOT CUBE)
        list(JOIN PACKS ", " PACKS_TEXT)
        message("No SVD file (${PACKS_TEXT}) - STM32Cube VSCode extension not installed, debugging without peripheral registers.")
        return()
    endif()

    foreach(PACK IN LISTS PACKS)
        message("Installing ${PACK} (SVD files) by STM32Cube extension ...")
        execute_process(COMMAND "${CUBE}" pack install ${PACK} RESULT_VARIABLE PACK_RESULT OUTPUT_QUIET)
        if(NOT PACK_RESULT EQUAL 0)
            message(WARNING "Installation of ${PACK} failed (${PACK_RESULT}).")
        endif()
    endforeach()

    # SVD files of the CMSIS pack root of the extension
    execute_process(COMMAND "${CUBE}" --get-current-value cmsis_pack_root
                    OUTPUT_VARIABLE PACK_ROOT_OUTPUT ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)

    if(PACK_ROOT_OUTPUT MATCHES "cmsis_pack_root=([^\r\n]+)")
        file(TO_CMAKE_PATH "${CMAKE_MATCH_1}" PACK_ROOT)
        file(GLOB_RECURSE PACK_SVD_FILES "${PACK_ROOT}/*.svd")
        list(APPEND VSCODE_SVD_FILES ${PACK_SVD_FILES})
        list(REMOVE_DUPLICATES VSCODE_SVD_FILES)
    endif()

    set(VSCODE_SVD_FILES "${VSCODE_SVD_FILES}" PARENT_SCOPE)
endfunction()


# ------------------------------------------------------------------------------
# Function: Prj_VSCode_CmakeTask
# Description: Task executing a CMake script of the platform.
#
# OUT_JSON  [out]: JSON task.
# IN_LABEL  [in]:  Label of the task.
# IN_DETAIL [in]:  Description of the task.
# IN_GROUP  [in]:  JSON group of the task ("" = none).
# IN_HIDE   [in]:  TRUE - task is hidden (preLaunchTask of debug configurations).
# IN_SCRIPT [in]:  Script (relative to project root).
# ARGN      [in]:  Script parameters (-D...).
# ------------------------------------------------------------------------------
function(Prj_VSCode_CmakeTask OUT_JSON IN_LABEL IN_DETAIL IN_GROUP IN_HIDE IN_SCRIPT)

    Prj_VSCode_JsonString(LABEL "${IN_LABEL}")
    Prj_VSCode_JsonString(DETAIL "${IN_DETAIL}")
    Prj_VSCode_JsonStringArray(ARGS ${ARGN} -P "${IN_SCRIPT}")

    set(MEMBERS label "${LABEL}" detail "${DETAIL}" type "\"process\"" command "\"cmake\"" args "${ARGS}")

    if(IN_GROUP)
        list(APPEND MEMBERS group "${IN_GROUP}")
    endif()

    if(IN_HIDE)
        list(APPEND MEMBERS hide "true")
    endif()

    list(APPEND MEMBERS problemMatcher "${VSCODE_PROBLEM_MATCHER}")

    Prj_VSCode_JsonObject(TASK ${MEMBERS})

    set(${OUT_JSON} "${TASK}" PARENT_SCOPE)
endfunction()


# ------------------------------------------------------------------------------
# Function: Prj_VSCode_PickInput
# Description: Input of tasks / debug configurations selected from a list.
#
# OUT_JSON       [out]: JSON input.
# IN_ID          [in]:  ID of the input (${input:<id>}).
# IN_DESCRIPTION [in]:  Description of the input.
# IN_DEFAULT     [in]:  Default option.
# ARGN           [in]:  Options.
# ------------------------------------------------------------------------------
function(Prj_VSCode_PickInput OUT_JSON IN_ID IN_DESCRIPTION IN_DEFAULT)

    Prj_VSCode_JsonString(ID "${IN_ID}")
    Prj_VSCode_JsonString(DESCRIPTION "${IN_DESCRIPTION}")
    Prj_VSCode_JsonString(DEFAULT "${IN_DEFAULT}")
    Prj_VSCode_JsonStringArray(OPTIONS ${ARGN})

    Prj_VSCode_JsonObject(INPUT id "${ID}" type "\"pickString\"" description "${DESCRIPTION}"
                                options "${OPTIONS}" default "${DEFAULT}")

    set(${OUT_JSON} "${INPUT}" PARENT_SCOPE)
endfunction()


# ------------------------------------------------------------------------------
# Function: Prj_VSCode_GenerateTasks
# Description: Generates tasks.json.
#
# IN_MCU_LIST       [in]: MCUs of the project.
# IN_DEBUG_MCU_LIST [in]: MCUs of the debug configurations (hidden build tasks).
# ------------------------------------------------------------------------------
function(Prj_VSCode_GenerateTasks IN_MCU_LIST IN_DEBUG_MCU_LIST)

    set(MCU_ARG "-DMCU=\${input:mcu}")
    set(TYPE_ARG "-DBUILD_TYPE=\${input:buildType}")
    set(SET_ARG "-DTEST_SET=\${input:testSet}")

    Prj_VSCode_CmakeTask(BUILD_TASK "EmBi: Build"
                         "Configure and build the project for the selected MCU and build type"
                         "{ \"kind\": \"build\", \"isDefault\": true }" FALSE "${VSCODE_BUILD_HANDLER}"
                         -DFUNCTION_ID=BUILD ${MCU_ARG} ${TYPE_ARG})

    Prj_VSCode_CmakeTask(REBUILD_TASK "EmBi: Clean rebuild"
                         "Configure without CMake cache and rebuild the project for the selected MCU and build type"
                         "\"build\"" FALSE "${VSCODE_BUILD_HANDLER}"
                         -DFUNCTION_ID=BUILD ${MCU_ARG} ${TYPE_ARG} -DBUILD_CLEAN=ON)

    Prj_VSCode_CmakeTask(FLASH_TASK "EmBi: Flash"
                         "Build the project for the selected MCU and build type, flash it by probe-rs and reset the MCU"
                         "" FALSE "${VSCODE_HANDLER}"
                         -DFUNCTION_ID=FLASH ${MCU_ARG} ${TYPE_ARG})

    Prj_VSCode_CmakeTask(UT_TASK "EmBi: Unit tests"
                         "Build unit tests of the selected MCU (host) and execute the selected test set"
                         "{ \"kind\": \"test\", \"isDefault\": true }" FALSE "${VSCODE_BUILD_HANDLER}"
                         -DFUNCTION_ID=TEST -DTEST_TYPE=UT "-DTARGET=\${input:mcu}" ${SET_ARG})

    Prj_VSCode_CmakeTask(IT_TASK "EmBi: Integration tests"
                         "Detect connected boards, build integration tests of the selected board and execute the selected test set"
                         "\"test\"" FALSE "${VSCODE_BUILD_HANDLER}"
                         -DFUNCTION_ID=TEST -DTEST_TYPE=IT "-DTARGET=\${input:itBoard}" ${SET_ARG})

    Prj_VSCode_CmakeTask(DETECT_TASK "EmBi: Detect connected boards"
                         "List boards connected to debug probes (Build/IntegrationTestBoards.json)"
                         "" FALSE "${VSCODE_BUILD_HANDLER}"
                         -DFUNCTION_ID=TEST_TARGET_LIST -DTEST_TYPE=IT)

    # Setup menu in the terminal
    Prj_VSCode_JsonString(SETUP_SH "bash ${VSCODE_SETUP_DIR}/Setup.sh")
    file(TO_NATIVE_PATH "${VSCODE_SETUP_DIR}/Setup.bat" SETUP_BAT_PATH)
    string(REPLACE "/" "\\" SETUP_BAT_PATH "${SETUP_BAT_PATH}")
    Prj_VSCode_JsonString(SETUP_BAT "${SETUP_BAT_PATH}")
    Prj_VSCode_JsonObject(SETUP_WINDOWS command "${SETUP_BAT}"
                          options "{ \"shell\": { \"executable\": \"cmd.exe\", \"args\": [ \"/d\", \"/c\" ] } }")
    Prj_VSCode_JsonObject(SETUP_TASK label "\"EmBi: Setup\"" detail "\"EmBi_Platform Setup menu\"" type "\"shell\""
                          command "${SETUP_SH}" windows "${SETUP_WINDOWS}"
                          presentation "{ \"focus\": true, \"panel\": \"dedicated\" }" problemMatcher "[]")

    set(TASKS "${BUILD_TASK}" "${REBUILD_TASK}" "${FLASH_TASK}" "${UT_TASK}" "${IT_TASK}" "${DETECT_TASK}" "${SETUP_TASK}")

    # Build of the debug firmware before debugging (preLaunchTask)
    foreach(MCU IN LISTS IN_DEBUG_MCU_LIST)
        Prj_VSCode_CmakeTask(MCU_TASK "EmBi: Build ${MCU}_Debug" "Configure and build ${MCU} Debug" "" TRUE
                             "${VSCODE_BUILD_HANDLER}" -DFUNCTION_ID=BUILD -DMCU=${MCU} -DBUILD_TYPE=Debug)
        list(APPEND TASKS "${MCU_TASK}")
    endforeach()

    Prj_VSCode_JsonArray(TASKS ${TASKS})

    # Inputs
    list(GET IN_DEBUG_MCU_LIST 0 DEFAULT_MCU)
    Prj_VSCode_PickInput(MCU_INPUT mcu "MCU" "${DEFAULT_MCU}" ${IN_MCU_LIST})
    Prj_VSCode_PickInput(TYPE_INPUT buildType "Build type" Debug Debug Release)

    # Boards - project boards, boards named by MCU (detected), all connected boards
    Prj_VSCode_GetProjectBoards(PROJECT_BOARDS)
    set(BOARDS ${PROJECT_BOARDS} ${IN_MCU_LIST})
    list(REMOVE_DUPLICATES BOARDS)
    list(GET BOARDS 0 DEFAULT_BOARD)
    Prj_VSCode_PickInput(BOARD_INPUT itBoard "Connected board (detected boards are named by MCU)"
                         "${DEFAULT_BOARD}" ${BOARDS} "${BUILD_HANDLER_ALL_BOARDS_TEXT}")

    Prj_VSCode_JsonObject(SET_INPUT id "\"testSet\"" type "\"promptString\""
                          description "\"Test set (name of the test, empty = all test sets)\"" default "\"\"")

    Prj_VSCode_JsonArray(INPUTS "${MCU_INPUT}" "${TYPE_INPUT}" "${BOARD_INPUT}" "${SET_INPUT}")

    Prj_VSCode_JsonObject(CONTENT version "\"2.0.0\"" options "{ \"cwd\": \"\${workspaceFolder}\" }"
                          presentation "{ \"panel\": \"dedicated\", \"clear\": true }"
                          tasks "${TASKS}" inputs "${INPUTS}")

    Prj_VSCode_WriteFile("tasks.json" "${CONTENT}")
endfunction()


# ------------------------------------------------------------------------------
# Function: Prj_VSCode_ProbeRsConfig
# Description: probe-rs debug configuration.
#
# OUT_JSON       [out]: JSON debug configuration.
# IN_NAME        [in]:  Name of the configuration.
# IN_REQUEST     [in]:  launch (flash and run) or attach.
# IN_MCU         [in]:  MCU.
# IN_PROGRAM     [in]:  Firmware (ELF).
# IN_PRELAUNCH   [in]:  preLaunchTask ("" = none).
# ------------------------------------------------------------------------------
function(Prj_VSCode_ProbeRsConfig OUT_JSON IN_NAME IN_REQUEST IN_MCU IN_PROGRAM IN_PRELAUNCH)

    Prj_VSCode_JsonString(NAME "${IN_NAME}")
    Prj_VSCode_JsonString(REQUEST "${IN_REQUEST}")
    Prj_VSCode_JsonString(PROGRAM "${IN_PROGRAM}")
    Prj_VSCode_JsonString(CHIP "${VSCODE_CHIP_${IN_MCU}}")

    if(VSCODE_PROBE_RS)
        Prj_VSCode_JsonString(RUNTIME "${VSCODE_PROBE_RS}")
    else()
        set(RUNTIME "\"probe-rs\"")
    endif()

    set(MEMBERS type "\"probe-rs-debug\"" request "${REQUEST}" name "${NAME}" cwd "\"\${workspaceFolder}\""
                runtimeExecutable "${RUNTIME}" runtimeArgs "[ \"dap-server\" ]" chip "${CHIP}")

    if(VSCODE_PROBE_${IN_MCU})
        Prj_VSCode_JsonString(PROBE "${VSCODE_PROBE_${IN_MCU}}")
        list(APPEND MEMBERS probe "${PROBE}")
    endif()

    list(APPEND MEMBERS connectUnderReset "false")

    if("${IN_REQUEST}" STREQUAL "launch")
        list(APPEND MEMBERS flashingConfig "{ \"flashingEnabled\": true, \"haltAfterReset\": false }")
    endif()

    # RTT channels of the firmware in the terminal of the debug session (no control block = not shown)
    set(CORE_MEMBERS coreIndex "0" programBinary "${PROGRAM}" rttEnabled "true")

    if(VSCODE_SVD_${IN_MCU})
        Prj_VSCode_JsonString(SVD "${VSCODE_SVD_${IN_MCU}}")
        list(APPEND CORE_MEMBERS svdFile "${SVD}")
    endif()

    Prj_VSCode_JsonObject(CORE ${CORE_MEMBERS})
    Prj_VSCode_JsonArray(CORES "${CORE}")
    list(APPEND MEMBERS coreConfigs "${CORES}" consoleLogLevel "\"Console\"")

    if(IN_PRELAUNCH)
        Prj_VSCode_JsonString(PRELAUNCH "${IN_PRELAUNCH}")
        list(APPEND MEMBERS preLaunchTask "${PRELAUNCH}")
    endif()

    Prj_VSCode_JsonObject(CONFIG ${MEMBERS})

    set(${OUT_JSON} "${CONFIG}" PARENT_SCOPE)
endfunction()


# ------------------------------------------------------------------------------
# Function: Prj_VSCode_GenerateLaunch
# Description: Generates launch.json - for every MCU debugging of the Debug
#              firmware (build, flash, run), attach to the running firmware and
#              debugging of an integration test firmware (built by task
#              Integration tests), debugging of unit tests (host gdb).
#
# IN_MCU_LIST       [in]: MCUs of the project.
# IN_DEBUG_MCU_LIST [in]: MCUs of the debug configurations.
# ------------------------------------------------------------------------------
function(Prj_VSCode_GenerateLaunch IN_MCU_LIST IN_DEBUG_MCU_LIST)

    Prj_VSCode_GetFirmwareName(Debug FIRMWARE)
    Prj_VSCode_GetTestFirmwares(UnitTests UT_FIRMWARES)
    Prj_VSCode_GetTestFirmwares(IntegrationTests IT_FIRMWARES)

    set(CONFIGS "")

    foreach(MCU IN LISTS IN_DEBUG_MCU_LIST)

        set(BUILD_DIR "\${workspaceFolder}/Build/${MCU}")

        Prj_VSCode_ProbeRsConfig(DEBUG_CONFIG "EmBi: Debug ${MCU}" launch ${MCU}
                                 "${BUILD_DIR}_Debug/${FIRMWARE}" "EmBi: Build ${MCU}_Debug")
        Prj_VSCode_ProbeRsConfig(ATTACH_CONFIG "EmBi: Attach ${MCU}" attach ${MCU}
                                 "${BUILD_DIR}_Debug/${FIRMWARE}" "")
        list(APPEND CONFIGS "${DEBUG_CONFIG}" "${ATTACH_CONFIG}")

        if(IT_FIRMWARES)
            Prj_VSCode_ProbeRsConfig(IT_CONFIG "EmBi: Debug integration test ${MCU}" launch ${MCU}
                                     "${BUILD_DIR}_IntegrationTest/IntegrationTests/\${input:itFirmware}" "")
            list(APPEND CONFIGS "${IT_CONFIG}")
        endif()

    endforeach()

    set(INPUTS "")

    if(UT_FIRMWARES)

        Prj_VSCode_JsonString(GDB "${VSCODE_GDB}")
        Prj_VSCode_JsonObject(PRETTY_PRINT description "\"Enable pretty-printing\""
                              text "\"-enable-pretty-printing\"" ignoreFailures "true")
        Prj_VSCode_JsonArray(SETUP_COMMANDS "${PRETTY_PRINT}")

        Prj_VSCode_JsonObject(UT_CONFIG type "\"cppdbg\"" request "\"launch\"" name "\"EmBi: Debug unit test\""
                              program "\"\${workspaceFolder}/Build/\${input:utMcu}_UnitTest/UnitTests/\${input:utFirmware}\""
                              cwd "\"\${workspaceFolder}\"" stopAtEntry "false" externalConsole "false"
                              MIMode "\"gdb\"" miDebuggerPath "${GDB}" setupCommands "${SETUP_COMMANDS}")
        list(APPEND CONFIGS "${UT_CONFIG}")

        list(GET IN_DEBUG_MCU_LIST 0 DEFAULT_MCU)
        list(GET UT_FIRMWARES 0 DEFAULT_UT)
        Prj_VSCode_PickInput(UT_MCU_INPUT utMcu "MCU of the unit tests (built by task EmBi: Unit tests)" "${DEFAULT_MCU}" ${IN_MCU_LIST})
        Prj_VSCode_PickInput(UT_INPUT utFirmware "Unit test" "${DEFAULT_UT}" ${UT_FIRMWARES})
        list(APPEND INPUTS "${UT_MCU_INPUT}" "${UT_INPUT}")

    endif()

    if(IT_FIRMWARES)
        list(GET IT_FIRMWARES 0 DEFAULT_IT)
        Prj_VSCode_PickInput(IT_INPUT itFirmware "Integration test firmware (built by task EmBi: Integration tests)"
                             "${DEFAULT_IT}" ${IT_FIRMWARES})
        list(APPEND INPUTS "${IT_INPUT}")
    endif()

    Prj_VSCode_JsonArray(CONFIGS ${CONFIGS})
    Prj_VSCode_JsonArray(INPUTS ${INPUTS})

    Prj_VSCode_JsonObject(CONTENT version "\"0.2.0\"" configurations "${CONFIGS}" inputs "${INPUTS}")

    Prj_VSCode_WriteFile("launch.json" "${CONTENT}")
endfunction()


# ------------------------------------------------------------------------------
# Function: Prj_VSCode_JsonValue
# Description: JSON text of a member of a parsed JSON object (string(JSON GET)
#              returns raw strings and ON / OFF for booleans).
#
# OUT_JSON   [out]: JSON value.
# IN_CONTENT [in]:  JSON object.
# IN_NAME    [in]:  Member name.
# ------------------------------------------------------------------------------
function(Prj_VSCode_JsonValue OUT_JSON IN_CONTENT IN_NAME)

    string(JSON VALUE_TYPE TYPE "${IN_CONTENT}" "${IN_NAME}")
    string(JSON VALUE GET "${IN_CONTENT}" "${IN_NAME}")

    if(VALUE_TYPE STREQUAL "STRING")
        Prj_VSCode_JsonString(VALUE "${VALUE}")
    elseif(VALUE_TYPE STREQUAL "BOOLEAN")
        if(VALUE)
            set(VALUE "true")
        else()
            set(VALUE "false")
        endif()
    elseif(VALUE_TYPE STREQUAL "NULL")
        set(VALUE "null")
    endif()

    set(${OUT_JSON} "${VALUE}" PARENT_SCOPE)
endfunction()


# ------------------------------------------------------------------------------
# Function: Prj_VSCode_GenerateSettings
# Description: Generates settings.json - settings of the platform are set,
#              other settings of an existing file are kept (comments and
#              trailing commas are removed, file is kept as settings.json.bak if
#              it was not generated).
# ------------------------------------------------------------------------------
function(Prj_VSCode_GenerateSettings)

    set(SETTINGS "{}")
    set(SETTINGS_FILE "${VSCODE_DIR}/settings.json")

    if(EXISTS "${SETTINGS_FILE}")

        file(READ "${SETTINGS_FILE}" OLD_SETTINGS)

        # JSON with comments - line comments and trailing commas removed
        string(REGEX REPLACE "\n[ \t]*//[^\n]*" "\n" OLD_SETTINGS "\n${OLD_SETTINGS}")
        string(REGEX REPLACE ",([ \t\r\n]*[]}])" "\\1" OLD_SETTINGS "${OLD_SETTINGS}")

        string(JSON SETTINGS_TYPE ERROR_VARIABLE SETTINGS_ERROR TYPE "${OLD_SETTINGS}")

        if(NOT SETTINGS_ERROR AND SETTINGS_TYPE STREQUAL "OBJECT")
            set(SETTINGS "${OLD_SETTINGS}")
        else()
            message(WARNING "settings.json cannot be parsed (${SETTINGS_ERROR}) - generated without its settings.")
        endif()

    endif()

    # Settings of the platform
    string(JSON SETTINGS SET "${SETTINGS}" "cmake.useCMakePresets" "\"always\"")
    string(JSON SETTINGS SET "${SETTINGS}" "cmake.configureOnOpen" "false")
    string(JSON SETTINGS SET "${SETTINGS}" "C_Cpp.default.configurationProvider" "\"ms-vscode.cmake-tools\"")

    # Merged object settings
    foreach(ITEM IN ITEMS "search.exclude|Build/**|true"
                          "files.watcherExclude|**/Build/**|true"
                          "files.associations|*.c.in|\"c\""
                          "files.associations|*.h.in|\"c\"")
        string(REPLACE "|" ";" ITEM "${ITEM}")
        list(GET ITEM 0 NAME)
        list(GET ITEM 1 KEY)
        list(GET ITEM 2 VALUE)

        string(JSON NAME_TYPE ERROR_VARIABLE NAME_ERROR TYPE "${SETTINGS}" "${NAME}")
        if(NAME_ERROR OR NOT NAME_TYPE STREQUAL "OBJECT")
            string(JSON SETTINGS SET "${SETTINGS}" "${NAME}" "{}")
        endif()
        string(JSON SETTINGS SET "${SETTINGS}" "${NAME}" "${KEY}" "${VALUE}")
    endforeach()

    # Default settings (kept if set)
    string(JSON RULERS ERROR_VARIABLE RULERS_ERROR GET "${SETTINGS}" "editor.rulers")
    if(RULERS_ERROR)
        # Max line length of the coding style
        string(JSON SETTINGS SET "${SETTINGS}" "editor.rulers" "[ 120 ]")
    endif()

    # Members of the formatted output
    string(JSON MEMBERS_CNT LENGTH "${SETTINGS}")
    math(EXPR MEMBERS_LAST "${MEMBERS_CNT} - 1")

    set(MEMBERS "")

    foreach(MEMBER_IDX RANGE ${MEMBERS_LAST})
        string(JSON NAME MEMBER "${SETTINGS}" ${MEMBER_IDX})
        Prj_VSCode_JsonValue(VALUE "${SETTINGS}" "${NAME}")
        string(REPLACE ";" "\\;" VALUE "${VALUE}")
        list(APPEND MEMBERS "${NAME}" "${VALUE}")
    endforeach()

    Prj_VSCode_JsonObject(CONTENT ${MEMBERS})

    Prj_VSCode_WriteFile("settings.json" "${CONTENT}")
endfunction()


# ------------------------------------------------------------------------------
# Function: Prj_VSCode_Init
# Description: Generates VSCode configuration of the project.
#
# IN_MCU_IDS [in]: Numerical IDs of the MCUs of debug configurations separated
#                  by comma (Prj_VSCode_PrintMcuList), 0 = all MCUs, empty =
#                  MCUs of connected boards (all MCUs if no board is detected).
# ------------------------------------------------------------------------------
function(Prj_VSCode_Init IN_MCU_IDS)

    Build_Handler_GetMcuList(MCU_LIST)

    string(REPLACE "," ";" MCU_IDS "${IN_MCU_IDS}")
    string(REPLACE " " "" MCU_IDS "${MCU_IDS}")
    list(REMOVE_ITEM MCU_IDS "")

    # Selected MCUs are checked before detection of boards
    set(DEBUG_MCU_LIST "")

    foreach(MCU_ID IN LISTS MCU_IDS)
        if(NOT "${MCU_ID}" STREQUAL "0")
            Build_Handler_GetListItem("${MCU_LIST}" "${MCU_ID}" "MCU" MCU)
            list(APPEND DEBUG_MCU_LIST "${MCU}")
        endif()
    endforeach()

    Prj_VSCode_FindTools()

    # Previous detection is not used
    file(REMOVE "${BUILD_HANDLER_BOARDS_FILE}")

    if(VSCODE_PROBE_RS)
        message("probe-rs: ${VSCODE_PROBE_RS}")

        # Probes of the MCUs - detection of connected boards (not required)
        execute_process(
            COMMAND           "${CMAKE_COMMAND}" ${BUILD_HANDLER_DETECT_ARGS} -DIT_PROBE_RS=${VSCODE_PROBE_RS}
                              -DIT_BOARDS_FILE=${BUILD_HANDLER_BOARDS_FILE} -P "${BUILD_HANDLER_IT_DETECT}"
            WORKING_DIRECTORY "${PROJECT_ROOT_PATH}"
            RESULT_VARIABLE   DETECT_RESULT
        )

        if(NOT DETECT_RESULT EQUAL 0)
            message(WARNING "Detection of connected boards failed - debug configurations without probes.")
        endif()
    else()
        message(WARNING "probe-rs not found - configure an integration test preset (artifact 'probe-rs') and repeat "
                        "the initialization, debug configurations use probe-rs from PATH.")
    endif()

    # MCUs of the debug configurations - all, selected or of connected boards
    if("0" IN_LIST MCU_IDS)

        set(DEBUG_MCU_LIST "${MCU_LIST}")

    elseif(NOT DEBUG_MCU_LIST)

        if(EXISTS "${BUILD_HANDLER_BOARDS_FILE}")
            Build_Handler_GetBoardList(BOARD_LIST PRESET_LIST)
            foreach(PRESET IN LISTS PRESET_LIST)
                string(REGEX REPLACE "_IntegrationTest$" "" MCU "${PRESET}")
                if("${MCU}" IN_LIST MCU_LIST)
                    list(APPEND DEBUG_MCU_LIST "${MCU}")
                endif()
            endforeach()
        endif()

        if(NOT DEBUG_MCU_LIST)
            message(WARNING "No connected board detected - debug configurations of all MCUs.")
            set(DEBUG_MCU_LIST "${MCU_LIST}")
        endif()

    endif()

    list(REMOVE_DUPLICATES DEBUG_MCU_LIST)

    IntegrationTesting_ReadMcuIdentification(IDENTIFIED_MCUS "${VSCODE_RAL_PRESETS_FILE}")

    # SVD files of MCUs without SVD from device family packs (STM32Cube extension)
    Prj_VSCode_InstallSvdPacks("${DEBUG_MCU_LIST}")

    message("")
    message("Debug configurations:")

    foreach(MCU IN LISTS DEBUG_MCU_LIST)

        Prj_VSCode_GetChip(${MCU} CHIP)
        Prj_VSCode_GetProbe(${MCU} PROBE)
        Prj_VSCode_FindSvd(${MCU} SVD)

        set(VSCODE_CHIP_${MCU}  "${CHIP}")
        set(VSCODE_PROBE_${MCU} "${PROBE}")
        set(VSCODE_SVD_${MCU}   "${SVD}")

        if(NOT PROBE)
            set(PROBE "no connected board")
        endif()
        if(NOT SVD)
            set(SVD "no SVD file")
        endif()

        message("  ${MCU}: chip ${CHIP}, probe ${PROBE}, ${SVD}")

    endforeach()

    message("")

    file(MAKE_DIRECTORY "${VSCODE_DIR}")

    Prj_VSCode_GenerateTasks("${MCU_LIST}" "${DEBUG_MCU_LIST}")
    Prj_VSCode_GenerateLaunch("${MCU_LIST}" "${DEBUG_MCU_LIST}")
    Prj_VSCode_GenerateSettings()

    Prj_VSCode_JsonObject(CPP_CONFIG name "\"EmBi\"" configurationProvider "\"ms-vscode.cmake-tools\"")
    Prj_VSCode_JsonArray(CPP_CONFIGS "${CPP_CONFIG}")
    Prj_VSCode_JsonObject(CPP_CONTENT configurations "${CPP_CONFIGS}" version "4")
    Prj_VSCode_WriteFile("c_cpp_properties.json" "${CPP_CONTENT}")

    Prj_VSCode_JsonStringArray(EXTENSIONS ${VSCODE_EXTENSIONS})
    Prj_VSCode_JsonObject(EXTENSIONS_CONTENT recommendations "${EXTENSIONS}")
    Prj_VSCode_WriteFile("extensions.json" "${EXTENSIONS_CONTENT}")

    message("")
    message("VSCode project initialized - open the project root folder in VSCode and install recommended extensions.")
endfunction()


# ------------------------------------------------------------------------------
# Function: Prj_VSCode_PrintMcuList
# Description: Prints MCUs of the project presets.
# ------------------------------------------------------------------------------
function(Prj_VSCode_PrintMcuList)

    Build_Handler_GetMcuList(MCU_LIST)
    Build_Handler_PrintList("All MCUs" ${MCU_LIST})
endfunction()


# ------------------------------------------------------------------------------
# Function: Prj_VSCode_Flash
# Description: Builds the project for the MCU, flashes the firmware by probe-rs
#              to the connected board with the MCU and resets the MCU (task
#              Flash).
#
# IN_MCU        [in]: MCU.
# IN_BUILD_TYPE [in]: Debug or Release.
# ------------------------------------------------------------------------------
function(Prj_VSCode_Flash IN_MCU IN_BUILD_TYPE)

    Build_Handler_GetMcuList(MCU_LIST)
    Build_Handler_GetListId("${MCU_LIST}" "${IN_MCU}" "MCU" MCU_ID)
    Build_Handler_Build(${MCU_ID} "${IN_BUILD_TYPE}")

    Prj_VSCode_FindTools()

    if(NOT VSCODE_PROBE_RS)
        message(FATAL_ERROR "probe-rs not found - configure an integration test preset (artifact 'probe-rs') or pass -DIT_PROBE_RS=<path>.")
    endif()

    IntegrationTesting_ReadMcuIdentification(IDENTIFIED_MCUS "${VSCODE_RAL_PRESETS_FILE}")
    Prj_VSCode_GetChip(${IN_MCU} CHIP)

    # Probe of the connected board with the MCU
    Build_Handler_DetectBoards()
    Prj_VSCode_GetProbe(${IN_MCU} PROBE)

    if(NOT PROBE)
        message(FATAL_ERROR "No connected board with MCU ${IN_MCU} detected.")
    endif()

    Prj_VSCode_GetFirmwareName(${IN_BUILD_TYPE} FIRMWARE)
    set(FIRMWARE_PATH "${BUILD_HANDLER_BUILD_DIR}/${IN_MCU}_${IN_BUILD_TYPE}/${FIRMWARE}")

    message("=====================================")
    message("Flash: ${FIRMWARE_PATH}")
    message("Chip ${CHIP}, probe ${PROBE}")
    message("=====================================")

    Build_Handler_Execute("Flashing of ${FIRMWARE}" "${VSCODE_PROBE_RS}" download --chip ${CHIP} --probe ${PROBE} "${FIRMWARE_PATH}")
    Build_Handler_Execute("Reset of ${IN_MCU}" "${VSCODE_PROBE_RS}" reset --chip ${CHIP} --probe ${PROBE})

    message("=====================================")
    message("Flash ${IN_MCU}_${IN_BUILD_TYPE} PASSED")
    message("=====================================")
endfunction()


#==============================================================================#
# Main functionality
#
# If the script is executed in script mode ( -P ), execution is started with
# first direct code out of function, thus functions execution has to be
# triggered.
#
# Example:
# cmake -DFUNCTION_ID="MCU_LIST"                                    -P Prj_VSCode_Handler.cmake : List MCUs of the project presets
# cmake -DFUNCTION_ID="INIT"  -DMCU_IDS="1,3"                       -P Prj_VSCode_Handler.cmake : Generate .vscode, debug configurations of MCUs 1 and 3 (0 = all, empty = connected boards)
# cmake -DFUNCTION_ID="FLASH" -DMCU=STM32F407xG -DBUILD_TYPE=Debug  -P Prj_VSCode_Handler.cmake : Build, flash and reset MCU STM32F407xG
#==============================================================================#
if(CMAKE_SCRIPT_MODE_FILE AND
   CMAKE_SCRIPT_MODE_FILE STREQUAL CMAKE_CURRENT_LIST_FILE)

    if("${FUNCTION_ID}" STREQUAL "MCU_LIST")

        Prj_VSCode_PrintMcuList()

    elseif("${FUNCTION_ID}" STREQUAL "INIT")

        Prj_VSCode_Init("${MCU_IDS}")

    elseif("${FUNCTION_ID}" STREQUAL "FLASH")

        if(NOT "${BUILD_TYPE}" MATCHES "^(Debug|Release)$")
            message(FATAL_ERROR "Required BUILD_TYPE '${BUILD_TYPE}' is not correct (Debug, Release).")
        endif()

        Prj_VSCode_Flash("${MCU}" "${BUILD_TYPE}")

    else()

        message(FATAL_ERROR "Unknown FUNCTION_ID '${FUNCTION_ID}'.")

    endif()

endif()
